### ISSUE TITLE
Hydra configuration editor is broken

### ISSUE THREAD

**Issue by aeneasr** [ory/docs#1901]
Gives a blank page

https://www.ory.sh/docs/hydra/reference/configuration-editor

---

URL: https://www.ory.sh/docs/hydra/reference/configuration-editor

Created at: 2024-08-29 22:59:33

**Comment by Laplace-Transformer** [comment]
The config.schema.json update has fixed this mostly. However there is still an issue with a regex.
To reproduce, open chrome console, tick"leak_sensitive_values" box view console.
![image](https://github.com/user-attachments/assets/ca4aa662-c0d9-40af-9112-a99b8abe0caa)

Can't find the source of the regex in github.

**Comment by alnr** [comment]
Huh? I fixed this a couple months ago?

**Comment by aeneasr** [comment]
But it's still broken: https://www.ory.sh/docs/hydra/reference/configuration-editor

**Comment by aeneasr** [comment]
<img width="557" alt="Image" src="https://github.com/user-attachments/assets/17db3915-3ec6-4029-ab21-d8918ca384f3" />
