### ISSUE TITLE
Hydra configuration editor crashes

### ISSUE THREAD

**Issue by tomekpapiernik** [ory/docs#722]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Trying to access the Hydra config editor the page crashes. 

https://www.ory.sh/docs/hydra/reference/configuration-editor

Originally reported by a community member:
https://ory-community.slack.com/archives/C012RBW0F18/p1648498590345789

### Reproducing the bug

1. go to https://www.ory.sh/docs/hydra/reference/configuration-editor
2. enjoy the show

### Version

current

**Comment by gen1us2k** [comment]
I found the issue that causes a webpage crash. The reason lies in spec/config.json. I fixed this with this patch
```diff
diff --git a/spec/config.json b/spec/config.json
index 0e8b7baa..c5ea89c6 100644
--- a/spec/config.json
+++ b/spec/config.json
@@ -1214,11 +1214,9 @@
     },
     "dangerous-allow-insecure-redirect-urls": {
       "type": "array",
-      "items": [
-        {
+      "items": {
           "type": "string"
-        }
-      ],
+      },
       "title": "Disable HTTPS enforcement for the provided redirect URLs.",
       "description": "DO NOT USE THIS IN PRODUCTION - Disable HTTPS enforcement for the provided redirect URLs. This is only available as CLI flag `--dangerous-allow-insecure-redirect-urls`."
     }
```
Also, I found that we use the master branch for config editors. I see two possible solutions:

1. use tags instead of master branch for configuration references
2. Fix config.json generators

**Comment by tomekpapiernik** [comment]
@gen1us2k 
I see that the page still fails whenever you try to access it. Could you please make sure that this behavior is fixed? Any other improvements or updates can be added in subsequent PRs. Thanks!

**Comment by gen1us2k** [comment]
@tomekpapiernik [PR](https://github.com/ory/hydra/pull/3105) is opened.
